### ISSUE TITLE
Parameter -Accessrights optional

### ISSUE THREAD

**Issue by ft3411** [MicrosoftDocs/office-docs-powershell#3971]
The parameter Accessrights in available only in Exchange 2010. And as far as I recall even there it was optional. In the current versions of exchange it doesnt exist anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87715e0a-1b04-5758-4d19-75f5081ca3ea
* Version Independent ID: 173e0488-62f0-e055-3e89-d0a48d181ace
* Content: [Remove-PublicFolderClientPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/sharing-and-collaboration/remove-publicfolderclientpermission?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/sharing-and-collaboration/Remove-PublicFolderClientPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/sharing-and-collaboration/Remove-PublicFolderClientPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Exchange cmdlet reference topics are now single sourced: one topic applies to all versions (where available). Note that the AccessRights parameter has this as the first sentence of the description:

> This parameter is available or functional only in Exchange Server 2010.

And, the **Applicable** attribute in the metadata of the parameter says (only) Exchange Server 2010.

```yaml
Type: MultiValuedProperty
Parameter Sets: (All)
Aliases:
Applicable: Exchange Server 2010
Required: True
Position: Named
Default value: None
Accept pipeline input: True
Accept wildcard characters: False
```

I checked a couple of different ways, and in Exchange 2010, the AccessRights parameter is required, which makes sense (you specify the user and the permissions that you want to remove).

Thanks for the feedback.
