### ISSUE TITLE
Set-TeamArchivedState -SetSpoSiteReadOnlyForMembers:$true "Failed to execute MS Graph backend request GetGroupSiteDriveRequest"

### ISSUE THREAD

**Issue by TGiersberg** [MicrosoftDocs/office-docs-powershell#7119]
```powershell
Set-TeamArchivedState -GroupId $team.GroupId -Archived:$true -SetSpoSiteReadOnlyForMembers:$true
```
gives error
```
Set-TeamArchivedState: Error occurred while executing
Code: Forbidden
Message: Failed to execute MS Graph backend request GetGroupSiteDriveRequest. The server failed to respond correctly. Response Code: Forbidden, Reason: Reason: Forbidden, Correlation headers: request-id: e88feabb-087c-4e4c-a345-527057db2c5c
client-request-id: e88feabb-087c-4e4c-a345-527057db2c5c
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"North Europe","Slice":"SliceC","Ring":"4","ScaleUnit":"004","RoleInstance":"AGSFE_IN_29"}}
Date: Wed, 20 Jan 2021 09:59:10 GMT
InnerError:
  RequestId: ecd116d7-3260-4320-9687-ac1e9d41f76a
  DateTimeStamp: 2021-01-20T09:59:10
HttpStatusCode: Forbidden
```
MicrosoftTeams 1.1.4
Powershell 7

```powershell
Set-TeamArchivedState -GroupId $team.GroupId -Archived:$true
```
Is working fine for the same team. `-SetSpoSiteReadOnlyForMembers:$true` also works for SOME teams but not others - strange.
